### ISSUE TITLE
'Ticket changed' notification

### ISSUE THREAD

**Issue by PangolinPaw** [OE-Development/Tickets#14]
After making changes to a ticket, e.g. reassigning it, the details.php page might benefit from a confirmation message.

This is particularly true of reassignment as there's currently nothing on the page to indicate who the ticket is currently assigned to.

**Comment by PangolinPaw** [comment]
A generic confirmation now appears. Client-side code (javascript, css or similar) might be used to adjust it's content to relate to the actual change made. E.g. 'Reassign to XXX'?

**Comment by PangolinPaw** [comment]
Fixed div at the bottom should juts notify that changes have been saved to the database - no need for the user to confirm.

**Comment by Jarlaxle1979** [comment]
Removed the notification - save on change not on click
