### ISSUE TITLE
Duplicate flag & status required

### ISSUE THREAD

**Issue by PangolinPaw** [OE-Development/Tickets#23]
Should an email be sent that relates to an issue already covered by a previous ticket, users need to be able to mark it as a duplicate. 

Duplicate tickets marked in this way are assigned a distinct 'DUPLICATE' status to prevent them appearing in the OPEN/IN_PROGRESS lists while also excluding them from any future counts of CLOSED tickets.

A duplicate's sender needs to be copied into the closing email sent to the first ticket's originator.

It may be dsirable to notify the sender of a duplicate ticket that OE are already aware of the issue & that they will be notified once it is resolved.

**Comment by PangolinPaw** [comment]
A 'mark as duplicate' button now appears on detail.php (https://github.com/OE-Development/Tickets/commit/26bb2c809509bb97008b2b8cedac622292923d25). Users will eventually be able to select a ticket from a drop-down list and merge the currently viewed ticket with that one.

Actual merge functionality that has yet to be written:
 - New 'DUPLICATE' status available in database
 - Record change of status in NOTES field (& display in front-end comments section)
 - Append originator of current ticket to FROM field of selected ticket (join by ';' to ensure future messages are sent to both new & old addresses)
 - New duplicate.html outgoing email template
 - Send duplicate.html email to originator

**Comment by Jarlaxle1979** [comment]
Is there anything I need to do on this one?  @PangolinPaw I should have built the button but you did that for me!  It looks like everything else is for you to do?
