### ISSUE TITLE
Reply in tickets to originator

### ISSUE THREAD

**Issue by Jarlaxle1979** [OE-Development/Tickets#28]
We require the ability to send an email with the original email attached to the originator.  It will need to contain the ticket_ID so that the reply can be matched back to the original ticket and record it as a comment.  A notification should be sent to the assignee.

**Comment by PangolinPaw** [comment]
I'm thinking this and other notifications could be built into index.php since yge system is designed to launch at boot.

Some sort of position: fixed div at the top of the page, similar to the cookie policy ones common on EU websites should work.

**Comment by PangolinPaw** [comment]
The notification of a reply should be covered by the notification in issue #14
