### ISSUE TITLE
Include files

### ISSUE THREAD

**Issue by Jarlaxle1979** [OE-Development/Tickets#30]
Add include files for common code across all pages.

**Comment by Jarlaxle1979** [comment]
Include file added.  Use this format <?php include 'xxx.php';?> where xxx.php is the new file to be included.  Will require a review of the content that will appear on multiple pages.

**Comment by PangolinPaw** [comment]
index.php now uses the _head_ and _title_ include files (https://github.com/OE-Development/Tickets/commit/73d3ef8f75a8b165523d71584b169e59036f96a7).

Still need to see what else can be consolidated into an include.
