### ISSUE TITLE
View of closed tickets

### ISSUE THREAD

**Issue by Jarlaxle1979** [OE-Development/Tickets#34]
- We need the ability for viewing closed tickets.  
- They should not be editable but all content should be viewable.
- Individual tickets should have the ability to be re-opened

**Comment by PangolinPaw** [comment]
Details of all tickets are permanently stored in the database so viewing closed tickets is easy enough.

However, I had imagined that once a ticket was closed, its original email (an outlook .msg file in //zeus/custserv/tickets/emails) and attachments  (also saved in a subdirectory) would be deleted to save excessive use of memory.

To add the ability to re-open a ticket, the associated files must be saved beyond its close date. Perhaps these files should be removed after a set period of time, e.g. 6 weeks after the closed date.

@Jarlaxle1979 what do you think?

**Comment by PangolinPaw** [comment]
Closed tickets can now be displayed on index.php and therefore selected to view in detail.php (commit https://github.com/OE-Development/Tickets/commit/b63ad6add3bb74ee5197fd12c3bdb1773c3fa9ef) but I still need to work on re-opening them once closed.

**Comment by PangolinPaw** [comment]
Since [this merge](https://github.com/OE-Development/Tickets/commit/41126cab438be34c68881171616cb23b05537f4e), any response to an email generated from a ticket (e.g. a close notification) sets the associated ticket's status to "IN_PROGRESS", providing a means for the originator to re-open a ticket.

**Comment by PangolinPaw** [comment]
Tested & found working as of https://github.com/OE-Development/Tickets/commit/84ad8ff39f5b529473ba1dd9735e914372825388
