### ISSUE TITLE
Assigned name drop down

### ISSUE THREAD

**Issue by Jarlaxle1979** [OE-Development/Tickets#36]
- When selecting a name that has no tickets assigned, a 'No tickets assigned' message should display.
- Where tickets are assigned, the name should be remain displayed in the drop down box.

**Comment by PangolinPaw** [comment]
@Jarlaxle1979 - At the moment the dropdown isn't functional as the include file is missing from the GitHub repo

**Comment by Jarlaxle1979** [comment]
Fixed - added include file to repo
