### ISSUE TITLE
Priority assignment

### ISSUE THREAD

**Issue by Jarlaxle1979** [OE-Development/Tickets#39]
We need the ability to be able to assign a priority to each ticket and for it to be visible in the list of an individuals tickets.  P1, P2 and P3.

**Comment by PangolinPaw** [comment]
Definitely a requirement. Off the top of my head I'd say this would require the following:
 - New 'PRIORITY' field in the tickets table of the database
    - And associated queries to display & edit it in the pages' PHP
 - New 'change priority' input on details.php
 - New priority indication on index.php

Regarding the last one; it could be a simple 'p1' string, icon or background colour, but what if the list of tickets was also order according to priority. i.e. most important at the top?

**Comment by PangolinPaw** [comment]
The priority for each ticket is now displayed alongside the ticket subject on index.php (https://github.com/OE-Development/Tickets/commit/16a73c6ecc639988258bc33c0ec55d98bd1e7354) and it can be viewed & changed on detail.php (https://github.com/OE-Development/Tickets/commit/c0b7bf46f3711ebf5affe622735309744f2e6f63).

Some placeholder styling has also been applied in main.css (https://github.com/OE-Development/Tickets/commit/9dd64a6e80330fa49b9e0d291d8758207bb8eef3) and the priority.php include file has been created (https://github.com/OE-Development/Tickets/commit/778e418526a24b79dedb228830522d7735ad5b46).
