### ISSUE TITLE
Select more than one person to assign a ticket to

### ISSUE THREAD

**Issue by Jarlaxle1979** [OE-Development/Tickets#46]
Multiple people could be working on the same item (particularly if that item is a 'project', not an 'amend') so the assignment shouldn't be exclusive.

Something like a list-box would work on detail.php, just need to figure out how to read/write that in the database.

![listbox](https://cloud.githubusercontent.com/assets/9369383/20894851/efdca2ca-bb0e-11e6-9819-12443ce14dc4.jpg)

**Comment by PangolinPaw** [comment]
We've decided this probably isn't needed. The new division of work in the restructured team makes assigning a task to one person at a time (& re-assigning or closing & making new tickets as appropriate) the simplest option.
