### ISSUE TITLE
Add/remove emails in From & CC fields

### ISSUE THREAD

**Issue by PangolinPaw** [OE-Development/Tickets#50]
The recipients of email notifications should be editable. Ideally individuals can be added & removed, but there should at least be a means to include or exclude the CC addresses (currently excluded from all notifications).

**Comment by Jarlaxle1979** [comment]
@PangolinPaw In addition this, we ideally need the ability to forward a message and add new recipients.

**Comment by PangolinPaw** [comment]
I'm struggling to get hold of the *CC* individuals' email addresses; the python-outlook interface just returns a string of names, unlike the *From* field.

For now, I'll leave the *CC*s out of all notifications and just work on the ability to add/remove people in the *From* field.

**Comment by PangolinPaw** [comment]
[This commit](https://github.com/OE-Development/Tickets/commit/4ed6c29289af2e96d612a26c46ec46c46ffa46f5) to detail.php introduces the ability to add and remove contacts from the FROM field of the database. Its from this field that "OE Ticket Creator.exe" fetches the recipients for all ticket notifications so users will now be able to control who is included.

I don't think there's any need to alter the CC field as these people won't typically want to be notified of ticket progress and in the cases where some do, users can just add them to the FROM field with this new functionality.
