### ISSUE TITLE
Outgoing attachments

### ISSUE THREAD

**Issue by PangolinPaw** [OE-Development/Tickets#53]
OE Team users need to be able to attach files to Reply messages

Off the top of my head, I think this would involve:
 - A file upload thingy (HTML & CSS)
 - A means to save the uploaded file in a sub-directory of the existing attachment folder for the ticket (PHP)
 - Logging the attached file's full path in the database so it's included in the Attachments div (SQLite)

**Comment by Jarlaxle1979** [comment]
@PangolinPaw Do I remember seeing a file upload thingy?   Is there any work for me on this one?

**Comment by PangolinPaw** [comment]
I was experimenting locally with an uploader, if I can just copy one of the existing buttons & pop-ups to add an upload dialogue then there's nothing required of you.
