### ISSUE TITLE
Extend Time Taken range

### ISSUE THREAD

**Issue by PangolinPaw** [OE-Development/Tickets#65]
The *Time Taken* & *Estimated Time* fields need to be extended so that larger projects can be tracked.

The new options will need to go up by smaller increments towards the uppe rend of the scale:
- 1 hour
- 0.25 days
- 0.5 days
- 0.75 days
- 1 day
- 1.25 days
- 1.5 days
 ... etc.
- 3 days
- 3.5 days
- 4 days
- 4.5 days
- 5 days
- 6 days
- 7 days
... etc.
- 15 days
- 20 days
- 25 days
- 30 days

**Comment by PangolinPaw** [comment]
James J suggested that the current minimum value (0.25 days) is too large for many tasks, such as part number changes. @Jarlaxle1979 what do you think of adding a 1 hour category (the database would still store this as a fraction of a day)?

**Comment by Jarlaxle1979** [comment]
@PangolinPaw yes this makes sense to me. I will add them in

**Comment by PangolinPaw** [comment]
@Jarlaxle1979 in that case can you also calculate what fraction of a typical day the 1hr option is equal to?

**Comment by Jarlaxle1979** [comment]
@PangolinPaw select name changed from "time" to "timeHours", "timeDays" and "timeWeeks"
$time_estimate changed to match e.g. $timeHours_estimate
