### ISSUE TITLE
Back link on detail

### ISSUE THREAD

**Issue by Jarlaxle1979** [OE-Development/Tickets#69]
@PangolinPaw I have had a thought about the back link and the fact that it goes back to your own tickets.  Would it be possible to change this to a drop down or similar with each team member on as well as unassigned so that you can choose which list to go back to?

**Comment by PangolinPaw** [comment]
Definitely possible, the links need only be adjusted to contain the right assignee username:

`<a href="index.php?assign=[username]>Back to [username]</a>`

These could be created from the usernames in the *team* table of the database, you can just insert the names into whatever HTML/CSS presentation you like.

I suggest a button which, when clicked sends the user to their own tickets, or on hover displays all the other users (and the *UNASSIGNED* option).
