### ISSUE TITLE
Attach files to a reply

### ISSUE THREAD

**Issue by Jarlaxle1979** [OE-Development/Tickets#80]
Reply dialogue needs to include a list of all files attached to the ticket.  These should be selectable (checkboxes?) and any that are selected need to be included in the reply email.

Requirements:
- Attachment checkboxes generated in a php loop
- Database field listing the attachments to include
- Ticket Creator adjusted to attach all listed files to generated reply

**Comment by PangolinPaw** [comment]
The attachments table of the database already includes a TYPE field that identifies whether a file was attached to the originating email or subsequently added through OE Tickets.

This field could be used to clearly label the attachments so selecting the required file is easier.

**Comment by PangolinPaw** [comment]
The latest commits to [ticketCreator.py](https://github.com/OE-Development/Tickets/commit/d424541a067837c27a9ef4ab200398fbdb802712) (and ["OE Ticket Creator.exe"](https://github.com/OE-Development/Tickets/commit/e05c56f9fae60400a5e56b6f000776feb78d6c29)) complete the changes necessary to enable this feature.
