### ISSUE TITLE
Time change

### ISSUE THREAD

**Issue by Jarlaxle1979** [OE-Development/Tickets#81]
Add 30 minutes to estimates and time spent

**Comment by Jarlaxle1979** [comment]
include file in detail.php - detailfunctions.php
drop down in detail.php

**Comment by Jarlaxle1979** [comment]
Complete except - value needs to be written out into fields on detail.php

**Comment by PangolinPaw** [comment]
Figured out how to get the 30min values to appear selected in the drop-down fields.
